[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn src.app.main:app --host 0.0.0.0 --port ${PORT} --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONPATH = "/app"